datasource:
  postgres:
    drive-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
    maximumPoolSize: 15
    class-mapper: classpath:mapper/postgres/**/*mapper.xml


server:
  port: 80